name: postalhub_tracker
description: "Postal Hub"

publish_to: 'none' 

version: 25.4.1605+8

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^3.12.1
  dynamic_color: ^1.7.0
  animations: ^2.0.8
  cloud_firestore: ^5.6.5
  path: ^1.9.0
  firebase_database: ^11.3.4
  flutter_markdown: ^0.7.1
  google_generative_ai: ^0.4.1
  loading_animation_widget: ^1.2.1
  intl: ^0.20.2
  #another_stepper: ^1.2.2
  shimmer: ^3.0.0
  flutter_custom_tabs: ^2.1.0
  url_launcher: ^6.3.0
  image_network: ^2.5.6
  cached_network_image: ^3.4.1
  simple_animations: ^5.1.0
  particles_flutter: ^1.0.1
  lucide_icons: ^0.257.0
  syncfusion_flutter_barcodes: ^29.1.39
  firebase_app_check: ^0.3.2+4
  carousel_slider: ^5.0.0
  google_fonts: ^6.2.1
  firebase_vertexai: ^1.4.0
  firebase_auth: ^5.5.1
  shared_preferences: ^2.5.3
  google_sign_in: ^6.3.0
  introduction_screen: ^3.1.17
  timelines_plus: ^1.0.6
  image_picker: ^1.1.2
  collection: ^1.19.1
  awesome_ripple_animation: ^2.0.0
  firebase_storage: ^12.4.6
  markdown_widget: ^2.3.2+8
  #go_router: ^15.1.1




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/images/postalhub_logo.jpg
  - assets/images/dev_pic1.png
  - assets/images/dev_pic.png
  - assets/images/How_to_use_1.png
  - assets/images/How_to_use_2.png
  - assets/images/favicon.png
  - assets/images/megaphones_purple.png
  - assets/images/carousel/1.png
  - assets/images/carousel/2.png
  - assets/images/carousel/3.png
  - assets/images/carousel/4.png
  - assets/images/carousel/5.png
  - assets/images/carousel/6.png
  - assets/images/profile_image_icon.jpg
  - assets/images/login/login.png
  - assets/images/login/register.png
  - assets/images/login/vector-3.png
  - assets/images/profile_card.jpg
  - assets/images/components/not_available.png
  - assets/images/components/parcel_mate.png
  - assets/images/components/parcel_not_found.png
  - assets/images/components/search_parcel.png
  - assets/images/components/smart_locker_comingsoon.png
  - assets/images/components/smart_locker_comingsoon1.png
  - assets/images/components/work_in_progress.png
  - assets/gif/not_found.gif
  - assets/gif/search.gif
  - assets/images/logo/google_logo.webp

  fonts:
      - family: GoogleSans
        fonts:
          - asset: assets/fonts/google_sans_regular.ttf
          - asset: assets/fonts/google_sans_italic.ttf
            style: italic
      - family: Kaleko
        fonts:
          - asset: assets/fonts/kaleko_regular.ttf
