name: postalhub_tracker
description: "Postalhub Tracker"

publish_to: 'none' 

version: 24.5.30+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^2.32.0
  dynamic_color: ^1.5.4
  animations: ^2.0.8
  cloud_firestore: ^4.14.0
  path: ^1.9.0
  firebase_storage: ^11.6.0
  firebase_database: ^10.5.5
  flutter_markdown: ^0.7.1
  google_generative_ai: ^0.4.1
  loading_animation_widget: ^1.2.1
  intl: ^0.17.0
  another_stepper: ^1.2.2
  shimmer: ^3.0.0
  flutter_custom_tabs: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/images/postalhub_logo.jpg
  - assets/images/dev_pic.png
  - assets/images/How_to_use_1.png
  - assets/images/How_to_use_2.png
  - assets/gif/not_found.gif
  - assets/gif/search.gif

  fonts:
      - family: GoogleSans
        fonts:
          - asset: assets/fonts/google_sans_regular.ttf
          - asset: assets/fonts/google_sans_italic.ttf
            style: italic
      - family: Kaleko
        fonts:
          - asset: assets/fonts/kaleko_regular.ttf
